spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/PunctualityRating
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  

# Настройки логирования
logging:
  level:
    com.example.airlineapp: DEBUG
    org.springframework.jdbc.core: TRACE

server:
  port: 8080